version: '2'

networks:
  app-tier:
    driver: bridge

services:
  Etcd:
    image: 'bitnami/etcd:3.5.13'
    ports:
      - "2379:2379"
      - "2380:2380"
    networks:
      - app-tier
    environment:
      - ETCD_ROOT_PASSWORD=3tcd_R00t_Passw0rd
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
volumes:
  etcd-data:
    driver: flocker
    driver_opts:
      size: "1GiB"
